name: Generate MIDI File

on:
  workflow_dispatch:
    inputs:
      key:
        type: choice
        description: 'Musical key to use for the melody'
        default: 'A Minor'
        options:
          - 'A Minor'
          - 'A# Minor'
          - 'B Minor'
          - 'C Minor'
          - 'C# Minor'
          - 'D Minor'
          - 'D# Minor'
          - 'E Minor'
          - 'F Minor'
          - 'F# Minor'
          - 'G Minor'
          - 'G# Minor'
      note-lengths:
        description: 'Lengths of notes to use (comma-separated list)'
        required: true
        default: '8,16'
      num-bars:
        description: 'Number of bars of music to create'
        required: true
        default: '2'
      filename:
        description: 'Name of the output MIDI file'
        required: true
        default: 'output.mid'

jobs:
  generate_midi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: MidiWriter

      - name: Build project
        run: dotnet build --configuration Release
        working-directory: MidiWriter
        
      - name: Generate MIDI file
        run: dotnet run --configuration Release -- ${{ github.event.inputs.key }} ${{ github.event.inputs.note-lengths }} ${{ github.event.inputs.num-bars }} ${{ github.event.inputs.filename }}
        working-directory: MidiWriter
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: midi-file
          path: ${{ github.event.inputs.filename }}
